"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import tempfile

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Production refuses to start without one. Local development gets a fresh
# random key each run, which is fine because nothing here keeps sessions.
SECRET_KEY = (os.getenv('SECRET_KEY') or '').strip()
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is off.')
    SECRET_KEY = get_random_secret_key()

# Only names this server really answers to. Render sets
# RENDER_EXTERNAL_HOSTNAME to the public name automatically; ALLOWED_HOSTS can
# add more (a custom domain), comma separated. localhost stays in because
# Render's own health check calls the service as localhost.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
_render_host = (os.getenv('RENDER_EXTERNAL_HOSTNAME') or '').strip()
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
ALLOWED_HOSTS += [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',')
                  if h.strip() and h.strip() != '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = []


# HTTPS. Render ends TLS at its proxy and passes the original scheme in
# X-Forwarded-Proto, so Django is told to trust that header. No redirect here:
# Render already sends http to https, and its health check calls plain http.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000


# Request counters for the rate limits. Kept on disk rather than in memory so
# every gunicorn worker shares one count. Render's disk is wiped on restart,
# which only resets the counters.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.getenv('THROTTLE_CACHE_DIR',
                              os.path.join(tempfile.gettempdir(), 'askfiles-throttle')),
        'OPTIONS': {'MAX_ENTRIES': 10000},
    }
}

# Every rate is tunable on Render without a code change. The per-client ones
# sit far above what anyone using the app can reach; the global ones are the
# cost cap across all users together.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'ai_client_burst': os.getenv('AI_RATE_CLIENT_BURST', '10/min'),
        'ai_client_hour': os.getenv('AI_RATE_CLIENT_HOUR', '120/hour'),
        'ai_client_day': os.getenv('AI_RATE_CLIENT_DAY', '500/day'),
        'ai_global_hour': os.getenv('AI_RATE_GLOBAL_HOUR', '1000/hour'),
        'ai_global_day': os.getenv('AI_RATE_GLOBAL_DAY', '5000/day'),
    },
}

# Largest question and device context ask-ai accepts. The app's context is a
# summary plus a few dozen file names, well under the default.
ASKFILES_MAX_QUESTION_CHARS = int(os.getenv('ASKFILES_MAX_QUESTION_CHARS', '1000'))
ASKFILES_MAX_CONTEXT_CHARS = int(os.getenv('ASKFILES_MAX_CONTEXT_CHARS', '32000'))
